### ISSUE TITLE
Why this repository is hosting on the NuxtLabs Organization ?

### ISSUE THREAD

**Issue by maximepvrt** [nuxtlabs/remark-mdc#63]

**Comment by Atinux** [comment]
Why do you think it should be in the UnJS organization?

We created the MDC syntax, parser at NuxtLabs for both Nuxt Content and Nuxt Studio.

**Comment by maximepvrt** [comment]
The concern is not about UnJS specifically, but rather why the repository is under NuxtLabs (which gives the impression of a private repo) instead of more community-oriented organizations like Nuxt, Nuxt Modules (but it's not a nuxt module), or UnJS.

I also wondered why Nuxt-MDC isn't directly under the Nuxt organization. Any specific reason for choosing Nuxt Modules (Collection of Nuxt modules from the community) over Nuxt org ?

**Comment by maximepvrt** [comment]
@Atinux And nuxtlabs contributions are added to nuxter :)

**Comment by Atinux** [comment]
Indeed!
